### ISSUE TITLE
Tweaking lesson 6.1

### ISSUE THREAD

**Issue by johnthad** [hojberg/mastering-react#24]
The import `import { history } from 'react-router/lib/BrowserHistory'` in `src/main.js` will fail with `Cannot find module` when runnig build. To fix this, make two changes in `src/main.js`:

```
import { history } from 'react-router/lib/BrowserHistory';
```

on line #6 to

```
import createBrowserHistory from 'history/lib/createBrowserHistory'
```

and

```
<Router history={history}>
```

on line #13 to

```
<Router history={createBrowserHistory()}>
```

Note that [history](https://www.npmjs.com/package/history) installed as part of `react-router` (despite what the `react-router` [installation instructions](https://github.com/rackt/react-router/) say):

```
├─┬ react-router@1.0.0-rc3 
│ ├─┬ history@1.12.3 
│ │ └── deep-equal@1.0.1 
│ ├── invariant@2.1.1 
│ └── warning@2.1.0 
```

Now the Storekeeper app builds, but the `Dashboard` and `Orders` links to not change their appearance when selected. To fix this, we must tell the links what the active class is. Looking in `styles/modules/_main_header.scss` we see that class is `selected`. So make the following additions to the link elements in `src/components/main_nav.js`:

```
      <nav className='main-nav'>
        <Link to='/dashboard' activeClassName='active'>Dashboard</Link>
        <Link to='/orders' activeClassName='active'>Orders</Link>
        <Link to='/catalog' activeClassName='active'>Catalog</Link>
      </nav>
```

**Comment by johnthad** [comment]
Here's a simpler approach:  When this video was made, the version of `react-router` was `1.0.0-beta3`. At the time of this writing, the current version is `1.0.0-rc3` and there have been _huge_ changes. Edit `package.json`, changing line #31 to force loading `react-router 1.0.0-beta3` _and only that version_: `"react-router": "1.0.0-beta3"`.

**Comment by hojberg** [comment]
Thanks for digging into this!
